### ISSUE TITLE
Reconnection of guests impossibile when host.protected set to true

### ISSUE THREAD

**Issue by benjiworld** [miroslavpejic85/mirotalksfu#175]
### Describe the bug

The first connection of a guest, (after the login of the presenter via username and password) works. The reconnection of the same guest, in the case of previous disconnection, doesn't work (while the presenter is still logged in). Trying  reconnecting the "who are you" page is presented, and no way to join the room anymore. Furthermore, the "sharing link" is wrong. In fact the link is https://owndomain.com/join/RoomName brings the guest to the "who are you" page, the correct link should be https://owndomain/join?room=RoomName

### Steps to reproduce

1. Use of self-hosted Mirotalk via docker compose. 
2. Customization of app/src/config.js
3. Set host.protected to true
4. Create an user (presenter) filling username and password
5. Login via web-browser by the presenter
6. Create a room and share the "correct" link to guests
7. Wait for guest to login
8. Logout of guest and try to re-login

### Expected behavior

1. The sharing link should be in the correct form, for quick forwarding;
2. Guests should able to login, to logout and re-login without problems

### Device

- [X] Android
- [ ] iPhone
- [X] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [X] Other desktop browser

### Reproducibility

No

### Additional context

Obviously impossible to reproduce on sfu.mirotalk.

**Comment by benjiworld** [comment]
After struggling for a while, I think I can reply to myself... The problem of impossible reconnection seems to live on "Redirect" section of app/src/config.js file (line 369). The redirection (when users opt-out) to the default /newroom probably triggers some internal check to force the client to login again. Changing the value to "true" and adding some external web page seems to fix the issue. The wrong shareable link instead is still there.

**Comment by miroslavpejic85** [comment]
> Furthermore, the "sharing link" is wrong. In fact the link is https://owndomain.com/join/RoomName brings the guest to the "who are you" page, the correct link should be https://owndomain/join?room=RoomName

You are right! Thank you, I'm going to fix it.

**Comment by miroslavpejic85** [comment]
@benjiworld, Should be fixed: Docker image [build status](https://github.com/miroslavpejic85/mirotalksfu/actions/runs/11648753676/job/32435558202).

![mirotalk-sfu-fix-share-link-host-protected](https://github.com/user-attachments/assets/13031b78-2d83-4ce2-acd3-54c3b0082728)

**Comment by benjiworld** [comment]
Thank you for the fix. The link is now correct, consider to extend the fix to the link proposed by "Your recent Room" in home page as well, because it still shows the old link. Furthermore, just notice that without the hint about the redirect section (see my first comment) the simple guest (no username and password) can still not re-login. Thanks a lot for this great app...
